apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"gitops.jenkins-x.io/pipeline":"cluster"},"name":"pipelineruns.tekton.dev"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[?(@.type==\"Succeeded\")].status","name":"Succeeded","type":"string"},{"JSONPath":".status.conditions[?(@.type==\"Succeeded\")].reason","name":"Reason","type":"string"},{"JSONPath":".status.startTime","name":"StartTime","type":"date"},{"JSONPath":".status.completionTime","name":"CompletionTime","type":"date"}],"group":"tekton.dev","names":{"categories":["tekton","tekton-pipelines"],"kind":"PipelineRun","plural":"pipelineruns","shortNames":["pr","prs"]},"scope":"Namespaced","subresources":{"status":{}},"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true},{"name":"v1beta1","served":true,"storage":false}]}}
  creationTimestamp: "2020-08-04T20:37:14Z"
  generation: 3
  labels:
    gitops.jenkins-x.io/pipeline: cluster
  name: pipelineruns.tekton.dev
  resourceVersion: "14301825"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/pipelineruns.tekton.dev
  uid: 0cb01df1-54c2-4fb0-9045-6efcfbdd9384
spec:
  conversion:
    strategy: None
  group: tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    kind: PipelineRun
    listKind: PipelineRunList
    plural: pipelineruns
    shortNames:
    - pr
    - prs
    singular: pipelinerun
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
      name: Reason
      type: string
    - jsonPath: .status.startTime
      name: StartTime
      type: date
    - jsonPath: .status.completionTime
      name: CompletionTime
      type: date
    name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
      name: Reason
      type: string
    - jsonPath: .status.startTime
      name: StartTime
      type: date
    - jsonPath: .status.completionTime
      name: CompletionTime
      type: date
    name: v1beta1
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-pipelines
    kind: PipelineRun
    listKind: PipelineRunList
    plural: pipelineruns
    shortNames:
    - pr
    - prs
    singular: pipelinerun
  conditions:
  - lastTransitionTime: "2020-08-04T20:37:14Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-08-04T20:37:14Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
  - v1alpha1
