apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jtfogarty:
          repos:
            jx3:
              required_status_checks:
                contexts:
                - promotion-build
            tst-go-jx:
              required_status_checks:
                contexts:
                - pr-build
      protect-tested-repos: true
    github:
      LinkURL: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      jtfogarty/jx3:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
      jtfogarty/tst-go-jx:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
    presubmits:
      jtfogarty/jx3:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jtfogarty/tst-go-jx:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jtfogarty/jx3: merge
        jtfogarty/tst-go-jx: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jtfogarty/jx3
        - jtfogarty/tst-go-jx
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jtfogarty/jx3
        - jtfogarty/tst-go-jx
      target_url: http://deck-jx.jx.docure.ai
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
