apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jtfogarty
    provider: https://github.com
    providerKind: github
    providerName: github
    repositories:
    - name: tst-go-jx
